version: '2'
services:
  docsan:
    container_name: docsan
    hostname: docsan
    image: ${REGISTRY}/ibfd/docsan:${VERSION}
    restart: always
    networks:
     - exposed
    ports:
     - 9997:8080
    volumes:
     - ${PWD}/docsan.json:/etc/docsan.json:ro
    cpu_quota: 50000
    mem_limit: '512m'
    dns:
     - ${DNS1_IP}
     - ${DNS2_IP}
    dns_search: ${DNS_SEARCH}
networks:
  exposed:
    external:
      name: ibfd_exposed

